import type { Icon } from "@phosphor-icons/react";
import {
  ArrowsClockwise,
  FileHtml,
  FileImage,
  FileJpg,
  FileMagnifyingGlass,
  FileMd,
  FilePdf,
  FilePpt,
  FileText,
  FileXls,
  Files,
  LockKey,
  LockKeyOpen,
  LockSimple,
  MagicWand,
  MicrosoftExcelLogo,
  MicrosoftPowerpointLogo,
  MicrosoftWordLogo,
  NumberCircleOne,
  PencilSimple,
  Scissors,
  Signature,
  Stack,
  TextT,
  Camera,
  Crop,
  DropHalf,
  PlugsConnected,
  Eye,
} from "@phosphor-icons/react";
import type { ToolId } from "@/lib/tools";

export const TOOL_ICONS: Record<ToolId, Icon> = {
  "merge-pdf": Stack,
  "split-pdf": Scissors,
  "organize-pdf": Files,
  "compress-pdf": FileMagnifyingGlass,
  "repair-pdf": MagicWand,
  "word-to-pdf": MicrosoftWordLogo,
  "powerpoint-to-pdf": MicrosoftPowerpointLogo,
  "excel-to-pdf": MicrosoftExcelLogo,
  "images-to-pdf": FileJpg,
  "html-to-pdf": FileHtml,
  "md-to-pdf": FileMd,
  "txt-to-pdf": FileText,
  "scan-to-pdf": Camera,
  "pdf-to-word": MicrosoftWordLogo,
  "pdf-to-powerpoint": MicrosoftPowerpointLogo,
  "pdf-to-excel": MicrosoftExcelLogo,
  "pdf-to-images": FileImage,
  "pdf-to-markdown": FileMd,
  "edit-pdf": PencilSimple,
  watermark: DropHalf,
  "page-numbers": NumberCircleOne,
  "crop-pdf": Crop,
  "rotate-pdf": ArrowsClockwise,
  "sign-pdf": Signature,
  "unlock-pdf": LockKeyOpen,
  "protect-pdf": LockKey,
  "redact-pdf": LockSimple,
  "ocr-pdf": TextT,
  "compare-pdf": Eye,
};

// Fallback used if a key is missing at runtime
export const DefaultToolIcon = FilePdf;
export const WorkflowIcon = PlugsConnected;
